// Generated by scripts/build-thumbnails.ts; do not edit.
export const THUMBS_VERSION = "dd3a99ab1d";
export const TEXT_THUMBS: ReadonlySet<string> = new Set(["connected-scatter","flowchart","icicle","marimekko","parallel","point-figure","spiral","stem-leaf","venn","word-cloud","word-tree"]);
