export type Locale = "pt" | "en";

export type VizFamily =
  | "comparison"
  | "distribution"
  | "relationship"
  | "time"
  | "composition"
  | "hierarchy"
  | "flow"
  | "geo"
  | "finance"
  | "text";

export type Bilingual = { pt: string; en: string };

export type VizEntry = {
  id: string;
  name: Bilingual;
  aliases: string[];
  family: VizFamily;
  complexity: "basic" | "intermediate" | "advanced";
  what: Bilingual;
  when: Bilingual;
  avoid: Bilingual;
  fields: Bilingual;
  tags: string[];
};

const bi = (pt: string, en: string): Bilingual => ({ pt, en });

const viz = (
  id: string,
  pt: string,
  en: string,
  family: VizFamily,
  complexity: VizEntry["complexity"],
  whatPt: string,
  whatEn: string,
  whenPt: string,
  whenEn: string,
  avoidPt: string,
  avoidEn: string,
  fieldsPt: string,
  fieldsEn: string,
  aliases: string[] = [],
  tags: string[] = [],
): VizEntry => ({
  id,
  name: bi(pt, en),
  aliases,
  family,
  complexity,
  what: bi(whatPt, whatEn),
  when: bi(whenPt, whenEn),
  avoid: bi(avoidPt, avoidEn),
  fields: bi(fieldsPt, fieldsEn),
  tags,
});

export const familyLabels: Record<VizFamily, Bilingual> = {
  comparison: bi("Comparação", "Comparison"),
  distribution: bi("Distribuição", "Distribution"),
  relationship: bi("Relações", "Relationships"),
  time: bi("Tempo", "Time"),
  composition: bi("Composição", "Composition"),
  hierarchy: bi("Hierarquia", "Hierarchy"),
  flow: bi("Fluxos e redes", "Flows & networks"),
  geo: bi("Geografia", "Geography"),
  finance: bi("Finanças e processos", "Finance & process"),
  text: bi("Texto e conceitos", "Text & concepts"),
};

/** Family swatches resolve to theme tokens defined in globals.css. */
export const familyColors: Record<VizFamily, string> = {
  comparison: "var(--fam-comparison)",
  distribution: "var(--fam-distribution)",
  relationship: "var(--fam-relationship)",
  time: "var(--fam-time)",
  composition: "var(--fam-composition)",
  hierarchy: "var(--fam-hierarchy)",
  flow: "var(--fam-flow)",
  geo: "var(--fam-geo)",
  finance: "var(--fam-finance)",
  text: "var(--fam-text)",
};

export const catalog: VizEntry[] = [
  viz("bar", "Gráfico de barras", "Bar chart", "comparison", "basic", "Compara magnitudes por meio do comprimento de barras em uma linha de base comum.", "Compares magnitudes using bar length on a shared baseline.", "Para ordenar e comparar categorias, sobretudo com rótulos longos.", "For ranking and comparing categories, especially with long labels.", "Evite excesso de categorias e eixos truncados sem indicação.", "Avoid too many categories and unmarked truncated axes.", "categoria + valor", "category + value", ["bar graph", "barras horizontais"], ["ranking", "categorias"]),
  viz("column", "Gráfico de colunas", "Column chart", "comparison", "basic", "É a versão vertical do gráfico de barras.", "The vertical version of a bar chart.", "Para poucas categorias ou períodos discretos em sequência.", "For a few categories or sequential discrete periods.", "Evite rótulos longos ou muitas colunas estreitas.", "Avoid long labels or too many narrow columns.", "categoria + valor", "category + value", ["vertical bar"], ["ranking"]),
  viz("grouped-bar", "Barras agrupadas", "Grouped bar chart", "comparison", "basic", "Coloca séries lado a lado dentro de cada categoria.", "Places series side by side within each category.", "Para comparar subgrupos em um conjunto pequeno de categorias.", "To compare subgroups across a small set of categories.", "Evite muitas séries: a leitura rapidamente se torna densa.", "Avoid many series; readability degrades quickly.", "categoria + série + valor", "category + series + value", ["clustered bar"], ["subgrupos"]),
  viz("stacked-bar", "Barras empilhadas", "Stacked bar chart", "composition", "basic", "Mostra o total e sua decomposição em segmentos.", "Shows a total and how segments compose it.", "Para comparar composição e total entre poucas categorias.", "To compare composition and totals across a few categories.", "Segmentos internos sem linha de base são difíceis de comparar.", "Internal segments without a baseline are hard to compare.", "categoria + parte + valor", "category + part + value", ["stacked column"], ["parte-todo"]),
  viz("normalized-bar", "Barras 100% empilhadas", "100% stacked bar", "composition", "basic", "Normaliza cada barra para comparar proporções.", "Normalizes each bar to compare proportions.", "Quando a composição relativa importa mais que os totais.", "When relative composition matters more than totals.", "Não use para comunicar diferenças absolutas.", "Do not use for absolute differences.", "categoria + parte + valor", "category + part + value", ["percent stacked"], ["percentual"]),
  viz("lollipop", "Lollipop", "Lollipop chart", "comparison", "basic", "Substitui a barra por uma haste e um ponto terminal.", "Replaces a bar with a stem and endpoint dot.", "Para rankings com bastante espaço negativo e valores bem separados.", "For airy rankings with clearly separated values.", "Barras são mais precisas para diferenças pequenas.", "Bars are more precise for small differences.", "categoria + valor", "category + value", ["lollipop plot"], ["ranking"]),
  viz("dot-plot", "Gráfico de pontos", "Dot plot", "comparison", "basic", "Representa valores por pontos em uma escala comum.", "Represents values as dots on a shared scale.", "Para comparações compactas, inclusive de duas medidas por categoria.", "For compact comparisons, including two measures per category.", "Evite pontos sobrepostos sem deslocamento ou transparência.", "Avoid overlapping dots without jitter or transparency.", "categoria + valor; série opcional", "category + value; optional series", ["Cleveland dot plot"], ["compacto"]),
  viz("dumbbell", "Dumbbell", "Dumbbell chart", "comparison", "intermediate", "Conecta dois valores da mesma categoria, enfatizando a diferença.", "Connects two values for each category, emphasizing the gap.", "Para antes/depois ou comparação de dois grupos.", "For before/after or two-group comparisons.", "Não funciona bem com mais de dois valores por categoria.", "It does not work well with more than two values per category.", "categoria + valor A + valor B", "category + value A + value B", ["connected dot plot"], ["antes-depois"]),
  viz("slope", "Slopegraph", "Slopegraph", "time", "intermediate", "Liga valores de duas ocasiões para revelar direção e intensidade da mudança.", "Links values at two moments to reveal direction and magnitude of change.", "Para mudanças entre exatamente dois pontos temporais.", "For changes between exactly two time points.", "Muitas linhas produzem cruzamentos e rótulos ilegíveis.", "Too many lines produce crossings and unreadable labels.", "entidade + momento + valor", "entity + moment + value", ["slope chart"], ["mudança"]),
  viz("bullet", "Bullet graph", "Bullet graph", "comparison", "intermediate", "Compara desempenho, meta e faixas qualitativas em pouco espaço.", "Compares performance, target, and qualitative ranges compactly.", "Para indicadores e painéis de metas.", "For KPIs and target dashboards.", "Exige legenda clara para meta e faixas.", "Requires clear labels for target and ranges.", "indicador + valor + meta + faixas", "metric + value + target + ranges", ["bullet chart"], ["meta", "KPI"]),
  viz("span", "Gráfico de intervalos", "Span chart", "comparison", "basic", "Exibe o intervalo entre valores mínimo e máximo.", "Displays the range between minimum and maximum values.", "Para comparar amplitudes entre categorias.", "To compare ranges between categories.", "Oculta a distribuição interna, média e mediana.", "It hides the internal distribution, mean, and median.", "categoria + mínimo + máximo", "category + minimum + maximum", ["range chart", "floating bar"], ["intervalo"]),
  viz("pareto", "Gráfico de Pareto", "Pareto chart", "comparison", "intermediate", "Combina categorias ordenadas e percentual acumulado.", "Combines ranked categories with a cumulative percentage.", "Para priorizar causas ou fatores de maior impacto.", "To prioritize the causes or factors with greatest impact.", "Não atribua causalidade apenas pela frequência.", "Do not infer causality from frequency alone.", "categoria + frequência", "category + frequency", [], ["priorização"]),
  viz("waterfall", "Cascata", "Waterfall chart", "finance", "intermediate", "Explica como contribuições positivas e negativas levam de um total inicial ao final.", "Explains how positive and negative contributions lead from an initial to a final total.", "Para decomposição financeira, variação e reconciliação.", "For financial bridges, changes, and reconciliation.", "Não é adequado para valores independentes.", "It is not suitable for independent values.", "etapa + variação; total opcional", "step + change; optional total", ["bridge chart"], ["variação"]),
  viz("butterfly", "Gráfico borboleta", "Butterfly chart", "comparison", "intermediate", "Coloca duas distribuições em lados opostos de um eixo central.", "Places two distributions on opposite sides of a central axis.", "Para comparar dois grupos nas mesmas categorias.", "To compare two groups across the same categories.", "Escalas assimétricas podem distorcer a comparação.", "Asymmetric scales can distort comparison.", "categoria + grupo A + grupo B", "category + group A + group B", ["tornado chart"], ["dois-grupos"]),
  viz("pictogram", "Pictograma", "Pictogram", "composition", "basic", "Usa unidades visuais repetidas para representar contagens ou frações.", "Uses repeated visual units to represent counts or fractions.", "Para comunicação pública de números simples e memoráveis.", "For public communication of simple, memorable quantities.", "Ícones parciais e escalados por área podem enganar.", "Partial icons and area scaling can mislead.", "categoria + contagem ou proporção", "category + count or proportion", ["isotype", "icon array"], ["comunicação"]),
  viz("radial-bar", "Barras radiais", "Radial bar chart", "comparison", "intermediate", "Dispõe barras ao redor de um círculo.", "Places bars around a circle.", "Para padrões cíclicos com muitas categorias e finalidade exploratória.", "For cyclical patterns with many categories and exploratory use.", "Comprimentos curvos são mais difíceis de comparar que barras lineares.", "Curved lengths are harder to compare than linear bars.", "categoria + valor", "category + value", ["circular barplot"], ["radial"]),
  viz("nightingale", "Rosa de Nightingale", "Nightingale rose", "comparison", "advanced", "Codifica valores pela área de setores com ângulos iguais.", "Encodes values using area in equal-angle sectors.", "Para fenômenos cíclicos quando a forma polar tem significado.", "For cyclical phenomena where polar form is meaningful.", "O raio não deve ser interpretado diretamente como valor.", "Radius must not be interpreted directly as value.", "categoria cíclica + valor", "cyclical category + value", ["coxcomb", "polar area"], ["radial"]),
  viz("histogram", "Histograma", "Histogram", "distribution", "basic", "Agrupa uma variável contínua em intervalos e conta observações.", "Bins a continuous variable and counts observations.", "Para investigar forma, concentração, lacunas e assimetria.", "To inspect shape, concentration, gaps, and skewness.", "A escolha dos intervalos pode alterar a história visual.", "Bin choice can change the visual story.", "uma variável quantitativa", "one quantitative variable", [], ["frequência"]),
  viz("density", "Curva de densidade", "Density plot", "distribution", "intermediate", "Estima uma distribuição contínua suavizada.", "Estimates a smoothed continuous distribution.", "Para comparar formas de distribuição com muitas observações.", "To compare distribution shapes with many observations.", "A largura de banda pode esconder ou inventar padrões.", "Bandwidth can hide or invent patterns.", "valor; grupo opcional", "value; optional group", ["KDE"], ["distribuição"]),
  viz("violin", "Violin plot", "Violin plot", "distribution", "intermediate", "Combina densidade espelhada com resumo da distribuição.", "Combines mirrored density with a distribution summary.", "Para comparar distribuições entre grupos.", "To compare distributions across groups.", "Mostre tamanho da amostra e cuidado com grupos pequenos.", "Show sample size and be cautious with small groups.", "grupo + valor", "group + value", [], ["grupos"]),
  viz("boxplot", "Boxplot", "Box plot", "distribution", "basic", "Resume mediana, quartis, dispersão e possíveis valores extremos.", "Summarizes median, quartiles, spread, and possible outliers.", "Para comparar distribuições de vários grupos compactamente.", "To compare many group distributions compactly.", "Pode esconder multimodalidade e tamanho da amostra.", "It can hide multimodality and sample size.", "grupo + valor", "group + value", ["box and whisker"], ["quartis"]),
  viz("ridgeline", "Ridgeline", "Ridgeline plot", "distribution", "intermediate", "Alinha densidades de vários grupos com leve sobreposição.", "Aligns densities for many groups with slight overlap.", "Para comparar padrões de muitas distribuições na mesma escala.", "To compare patterns across many distributions on one scale.", "A sobreposição sacrifica a leitura exata.", "Overlap sacrifices exact reading.", "grupo + valor", "group + value", ["joyplot"], ["múltiplos-grupos"]),
  viz("beeswarm", "Beeswarm", "Beeswarm plot", "distribution", "intermediate", "Mostra cada observação evitando sobreposição lateral.", "Shows every observation while avoiding lateral overlap.", "Para amostras pequenas ou médias onde pontos individuais importam.", "For small or medium samples where individual points matter.", "Fica pesado com milhares de observações.", "It becomes heavy with thousands of observations.", "grupo + valor", "group + value", ["swarm plot"], ["observações"]),
  viz("strip", "Strip plot", "Strip plot", "distribution", "basic", "Exibe observações individuais com deslocamento opcional.", "Displays individual observations with optional jitter.", "Para revelar a distribuição subjacente em amostras menores.", "To reveal the underlying distribution in smaller samples.", "Sem jitter, valores repetidos podem desaparecer.", "Without jitter, repeated values may disappear.", "grupo + valor", "group + value", ["jitter plot"], ["observações"]),
  viz("stem-leaf", "Diagrama de ramo e folhas", "Stem-and-leaf plot", "distribution", "basic", "Preserva valores individuais enquanto mostra a forma da distribuição.", "Preserves individual values while showing distribution shape.", "Para conjuntos pequenos em contexto educacional.", "For small datasets in educational contexts.", "Não escala para grandes conjuntos ou muitos dígitos.", "It does not scale to large datasets or many digits.", "uma variável quantitativa", "one quantitative variable", [], ["educacional"]),
  viz("population-pyramid", "Pirâmide populacional", "Population pyramid", "distribution", "basic", "Compara duas populações ao longo de classes ordenadas, geralmente idade.", "Compares two populations across ordered classes, usually age.", "Para estruturas etárias ou distribuições espelhadas.", "For age structures or mirrored distributions.", "Use a mesma escala nos dois lados.", "Use the same scale on both sides.", "classe + grupo A + grupo B", "class + group A + group B", [], ["demografia"]),
  viz("error-bars", "Barras de erro", "Error bars", "distribution", "intermediate", "Representa incerteza ou variabilidade ao redor de uma estimativa.", "Represents uncertainty or variability around an estimate.", "Para intervalos de confiança, erro padrão ou dispersão claramente identificados.", "For clearly identified confidence intervals, standard error, or spread.", "Nunca omita o significado do intervalo; pontos brutos podem ser melhores.", "Never omit what the interval means; raw points may be better.", "estimativa + limite inferior + superior", "estimate + lower + upper bound", [], ["incerteza"]),
  viz("scatter", "Dispersão", "Scatter plot", "relationship", "basic", "Posiciona observações por duas variáveis quantitativas.", "Positions observations by two quantitative variables.", "Para investigar associação, clusters e valores extremos.", "To investigate association, clusters, and outliers.", "Correlação visual não demonstra causalidade; trate sobreposição.", "Visual correlation does not prove causation; address overplotting.", "X quantitativo + Y quantitativo", "quantitative X + quantitative Y", [], ["correlação"]),
  viz("bubble", "Gráfico de bolhas", "Bubble chart", "relationship", "intermediate", "Acrescenta tamanho e, opcionalmente, cor a um gráfico de dispersão.", "Adds size and optionally color to a scatter plot.", "Para explorar três ou quatro variáveis simultaneamente.", "To explore three or four variables at once.", "Dimensione pela área, apresente legenda e controle sobreposição.", "Scale by area, provide a legend, and control overlap.", "X + Y + tamanho; categoria opcional", "X + Y + size; optional category", [], ["multivariado"]),
  viz("connected-scatter", "Dispersão conectada", "Connected scatter", "relationship", "intermediate", "Conecta pontos por uma ordem, combinando relação e trajetória.", "Connects points by an order, combining relationship and trajectory.", "Para trajetórias em duas métricas ao longo do tempo.", "For trajectories across two metrics over time.", "A direção precisa ser indicada e poucos grupos devem ser mostrados.", "Direction must be indicated and few groups should be shown.", "X + Y + ordem", "X + Y + order", [], ["trajetória"]),
  viz("heatmap", "Mapa de calor", "Heatmap", "relationship", "basic", "Codifica valores de uma matriz por intensidade de cor.", "Encodes matrix values through color intensity.", "Para padrões gerais em duas dimensões categóricas ou discretizadas.", "For broad patterns across two categorical or binned dimensions.", "Não dependa de cor para leitura exata; normalize quando necessário.", "Do not rely on color for exact reading; normalize when needed.", "linha + coluna + valor", "row + column + value", [], ["matriz"]),
  viz("correlogram", "Correlograma", "Correlogram", "relationship", "intermediate", "Resume correlações entre pares de variáveis numéricas.", "Summarizes pairwise correlations among numeric variables.", "Para triagem multivariada antes de análises mais profundas.", "For multivariate screening before deeper analysis.", "Muitas variáveis tornam rótulos e padrões ilegíveis.", "Too many variables make labels and patterns unreadable.", "três ou mais variáveis quantitativas", "three or more quantitative variables", ["correlation matrix"], ["correlação"]),
  viz("parallel", "Coordenadas paralelas", "Parallel coordinates", "relationship", "advanced", "Traça cada observação através de vários eixos paralelos.", "Plots each observation across multiple parallel axes.", "Para explorar perfis multivariados e selecionar padrões.", "To explore multivariate profiles and brush patterns.", "Muitas linhas geram um gráfico espaguete; normalize e filtre.", "Too many lines create spaghetti; normalize and filter.", "múltiplas variáveis quantitativas", "multiple quantitative variables", [], ["multivariado"]),
  viz("radar", "Radar", "Radar chart", "relationship", "basic", "Distribui indicadores em eixos radiais para formar perfis.", "Distributes indicators over radial axes to form profiles.", "Para poucos perfis com indicadores na mesma direção semântica.", "For a few profiles whose metrics share semantic direction.", "Comparação de áreas é imprecisa; padronize escalas.", "Area comparison is imprecise; standardize scales.", "entidade + três ou mais indicadores", "entity + three or more metrics", ["spider chart"], ["perfil"]),
  viz("line", "Gráfico de linhas", "Line chart", "time", "basic", "Conecta valores ordenados para mostrar continuidade e tendência.", "Connects ordered values to show continuity and trend.", "Para séries temporais ou sequências contínuas.", "For time series or continuous sequences.", "Muitas séries viram espaguete; não conecte categorias sem ordem.", "Too many series create spaghetti; do not connect unordered categories.", "tempo/ordem + valor; série opcional", "time/order + value; optional series", [], ["tendência"]),
  viz("area", "Gráfico de área", "Area chart", "time", "basic", "Preenche a área sob uma linha para enfatizar volume acumulado.", "Fills the area under a line to emphasize accumulated magnitude.", "Para uma série não negativa em que volume importa.", "For one non-negative series where magnitude matters.", "O preenchimento pode exagerar diferenças e ocultar linhas de base.", "Fill can exaggerate differences and obscure baselines.", "tempo + valor", "time + value", [], ["tendência"]),
  viz("stacked-area", "Área empilhada", "Stacked area", "time", "intermediate", "Mostra evolução do total e de suas partes ao longo do tempo.", "Shows how a total and its parts evolve over time.", "Para poucas séries positivas com composição temporal.", "For a few positive series with temporal composition.", "Somente a série inferior possui linha de base estável.", "Only the bottom series has a stable baseline.", "tempo + parte + valor", "time + part + value", [], ["composição temporal"]),
  viz("streamgraph", "Streamgraph", "Streamgraph", "time", "advanced", "Centraliza áreas empilhadas para criar um fluxo orgânico de composição.", "Centers stacked areas to create an organic composition flow.", "Para padrões gerais em muitas séries ao longo do tempo.", "For broad patterns across many series over time.", "É expressivo, mas inadequado para leitura de valores exatos.", "It is expressive but unsuitable for exact value reading.", "tempo + categoria + valor", "time + category + value", ["theme river"], ["composição temporal"]),
  viz("calendar", "Calendário de calor", "Calendar heatmap", "time", "intermediate", "Organiza dias no formato de calendário e usa cor para intensidade.", "Organizes days as a calendar and uses color for intensity.", "Para sazonalidade diária, hábitos e atividade.", "For daily seasonality, habits, and activity.", "Não funciona bem para períodos curtos ou múltiplas medidas.", "It is weak for short periods or multiple measures.", "data diária + valor", "daily date + value", [], ["sazonalidade"]),
  viz("spiral", "Gráfico espiral", "Spiral plot", "time", "advanced", "Dispõe uma série ao longo de uma espiral para destacar periodicidade.", "Places a series along a spiral to highlight periodicity.", "Para ciclos longos com repetição sazonal.", "For long cycles with seasonal repetition.", "Valores exatos e comparação entre voltas são difíceis.", "Exact values and comparisons across turns are difficult.", "tempo + valor", "time + value", [], ["cíclico"]),
  viz("timeline", "Linha do tempo", "Timeline", "time", "basic", "Organiza eventos ao longo de uma escala temporal.", "Organizes events along a temporal scale.", "Para comunicar sequência, duração e marcos.", "To communicate sequence, duration, and milestones.", "Evite aglomeração de eventos sem níveis ou filtros.", "Avoid crowded events without lanes or filters.", "data/início + evento; fim opcional", "date/start + event; optional end", [], ["eventos"]),
  viz("gantt", "Gantt", "Gantt chart", "time", "intermediate", "Exibe duração e sobreposição de tarefas em um cronograma.", "Displays task duration and overlap in a schedule.", "Para planejamento de projetos e dependências.", "For project planning and dependencies.", "Projetos muito detalhados exigem filtros e hierarquia.", "Very detailed projects require filters and hierarchy.", "tarefa + início + fim; grupo/dependência opcionais", "task + start + end; optional group/dependency", [], ["projeto"]),
  viz("pie", "Gráfico de pizza", "Pie chart", "composition", "basic", "Divide um total em setores proporcionais.", "Divides a whole into proportional sectors.", "Para duas a cinco partes com diferenças evidentes e total significativo.", "For two to five parts with clear differences and a meaningful whole.", "Evite muitas fatias, valores próximos, negativos ou totais artificiais.", "Avoid many slices, close values, negatives, or artificial totals.", "categoria + valor positivo", "category + positive value", [], ["parte-todo"]),
  viz("donut", "Gráfico de rosca", "Donut chart", "composition", "basic", "É uma pizza com centro livre para anotação.", "A pie chart with a center available for annotation.", "Para composição simples com poucas partes.", "For simple composition with few parts.", "Tem as mesmas limitações perceptivas do gráfico de pizza.", "It shares the perceptual limitations of pie charts.", "categoria + valor positivo", "category + positive value", ["doughnut"], ["parte-todo"]),
  viz("treemap", "Treemap", "Treemap", "hierarchy", "intermediate", "Usa retângulos aninhados cuja área representa valor.", "Uses nested rectangles whose area represents value.", "Para composição hierárquica com muitas partes.", "For hierarchical composition with many parts.", "Áreas semelhantes são difíceis de comparar; rótulos podem desaparecer.", "Similar areas are hard to compare; labels may disappear.", "hierarquia + valor", "hierarchy + value", [], ["hierarquia"]),
  viz("sunburst", "Sunburst", "Sunburst", "hierarchy", "intermediate", "Representa níveis hierárquicos como anéis concêntricos.", "Represents hierarchy levels as concentric rings.", "Para explorar caminhos e profundidade de uma árvore.", "To explore paths and depth in a tree.", "Setores externos pequenos são difíceis de ler.", "Small outer sectors are hard to read.", "hierarquia + valor", "hierarchy + value", [], ["hierarquia", "radial"]),
  viz("circle-packing", "Empacotamento de círculos", "Circle packing", "hierarchy", "intermediate", "Aninha círculos para comunicar agrupamento e tamanho.", "Nests circles to communicate grouping and size.", "Para visão exploratória e identidade visual de hierarquias.", "For exploratory and expressive views of hierarchies.", "Desperdiça espaço e é menos preciso que treemap.", "It wastes space and is less precise than a treemap.", "hierarquia + valor", "hierarchy + value", [], ["hierarquia"]),
  viz("icicle", "Icicle", "Icicle chart", "hierarchy", "intermediate", "Empilha níveis hierárquicos em faixas retangulares.", "Stacks hierarchy levels as rectangular bands.", "Para comparar profundidade e tamanho com boa linha de base.", "To compare depth and size with a stable baseline.", "Árvores profundas precisam de zoom ou drill-down.", "Deep trees require zoom or drill-down.", "hierarquia + valor", "hierarchy + value", ["partition chart"], ["hierarquia"]),
  viz("marimekko", "Marimekko", "Marimekko chart", "composition", "advanced", "Usa largura e altura de segmentos para duas proporções simultâneas.", "Uses segment width and height for two proportions at once.", "Para participação de mercado e composição em duas dimensões.", "For market share and two-dimensional composition.", "Área é difícil de comparar e exige anotações cuidadosas.", "Area is hard to compare and requires careful annotation.", "categoria X + categoria Y + valor", "X category + Y category + value", ["mosaic", "mekko"], ["duas-dimensões"]),
  viz("waffle", "Waffle chart", "Waffle chart", "composition", "basic", "Preenche uma grade de unidades para representar porcentagens.", "Fills a unit grid to represent percentages.", "Para uma proporção simples destinada ao público geral.", "For a simple proportion aimed at a general audience.", "Arredondamento e muitos grupos reduzem a precisão.", "Rounding and too many groups reduce precision.", "categoria + proporção", "category + proportion", [], ["percentual"]),
  viz("venn", "Diagrama de Venn", "Venn diagram", "composition", "basic", "Mostra interseções entre conjuntos por áreas sobrepostas.", "Shows set intersections through overlapping areas.", "Para dois ou três conjuntos com interseções conceituais simples.", "For two or three sets with simple conceptual intersections.", "Não use para muitos conjuntos ou áreas quantitativas imprecisas.", "Do not use for many sets or imprecise quantitative areas.", "itens e pertencimento a conjuntos", "items and set membership", [], ["conjuntos"]),
  viz("upset", "UpSet plot", "UpSet plot", "composition", "advanced", "Representa interseções de múltiplos conjuntos por matriz e barras.", "Represents many set intersections using a matrix and bars.", "Quando há quatro ou mais conjuntos ou interseções complexas.", "When there are four or more sets or complex intersections.", "É menos familiar e exige orientação de leitura.", "It is less familiar and needs reading guidance.", "itens e pertencimento a conjuntos", "items and set membership", [], ["conjuntos"]),
  viz("tree", "Diagrama de árvore", "Tree diagram", "hierarchy", "basic", "Mostra relações pai-filho por nós e conexões.", "Shows parent-child relationships through nodes and links.", "Para estruturas organizacionais, taxonomias e decisões.", "For organizations, taxonomies, and decisions.", "Árvores largas ou profundas precisam de colapso e busca.", "Wide or deep trees need collapse and search.", "id + pai + rótulo", "id + parent + label", [], ["hierarquia"]),
  viz("dendrogram", "Dendrograma", "Dendrogram", "hierarchy", "intermediate", "Representa agrupamentos hierárquicos e a ordem de fusão.", "Represents hierarchical clusters and merge order.", "Para resultados de clusterização e similaridade.", "For clustering and similarity results.", "A geometria depende do método e da métrica escolhidos.", "Geometry depends on the chosen method and metric.", "objetos + matriz de distância ou árvore", "objects + distance matrix or tree", [], ["cluster"]),
  viz("sankey", "Diagrama de Sankey", "Sankey diagram", "flow", "intermediate", "Dimensiona conexões para mostrar fluxos entre etapas ou entidades.", "Scales links to show flows among stages or entities.", "Para energia, orçamento, migração, jornadas e conversões.", "For energy, budgets, migration, journeys, and conversions.", "Muitos nós e cruzamentos reduzem drasticamente a leitura.", "Too many nodes and crossings sharply reduce readability.", "origem + destino + peso", "source + target + weight", [], ["fluxo"]),
  viz("alluvial", "Diagrama aluvial", "Alluvial diagram", "flow", "advanced", "Mostra como grupos mudam entre dimensões categóricas sucessivas.", "Shows how groups change across successive categorical dimensions.", "Para trajetórias de categorias em várias etapas.", "For category trajectories across several stages.", "Ordenação inadequada cria cruzamentos desnecessários.", "Poor ordering creates unnecessary crossings.", "etapas categóricas + peso", "categorical stages + weight", ["parallel sets"], ["fluxo"]),
  viz("chord", "Diagrama de cordas", "Chord diagram", "flow", "advanced", "Conecta categorias ao redor de um círculo com faixas proporcionais.", "Connects categories around a circle with proportional ribbons.", "Para relações bidirecionais em uma rede pequena e densa.", "For bidirectional relationships in a small dense network.", "Comparar larguras e direções é difícil; limite o número de nós.", "Comparing widths and directions is hard; limit node count.", "origem + destino + peso", "source + target + weight", ["ribbon chord"], ["rede"]),
  viz("non-ribbon-chord", "Cordas sem faixas", "Non-ribbon chord", "flow", "advanced", "Usa linhas, em vez de faixas, para conexões circulares.", "Uses lines instead of ribbons for circular connections.", "Para destacar topologia quando pesos são secundários.", "To emphasize topology when weights are secondary.", "Redes densas viram um emaranhado visual.", "Dense networks become a visual tangle.", "origem + destino; peso opcional", "source + target; optional weight", [], ["rede"]),
  viz("network", "Diagrama de rede", "Network diagram", "flow", "intermediate", "Representa entidades como nós e relações como arestas.", "Represents entities as nodes and relationships as edges.", "Para estrutura social, citações, sistemas e dependências.", "For social structure, citations, systems, and dependencies.", "Layout não prova importância; explique tamanho, cor e posição.", "Layout does not prove importance; explain size, color, and position.", "nós + origem/destino; peso opcional", "nodes + source/target; optional weight", ["node-link"], ["grafo"]),
  viz("arc", "Diagrama de arcos", "Arc diagram", "flow", "intermediate", "Ordena nós em uma linha e desenha relações como arcos.", "Orders nodes on a line and draws relationships as arcs.", "Para revelar padrões de conexão dependentes da ordem.", "To reveal connection patterns dependent on ordering.", "A ordem escolhida altera fortemente o padrão.", "The chosen order strongly changes the pattern.", "nó ordenado + origem + destino", "ordered node + source + target", [], ["grafo"]),
  viz("edge-bundling", "Agrupamento de arestas", "Edge bundling", "flow", "advanced", "Agrupa conexões semelhantes para reduzir o ruído de redes densas.", "Bundles similar connections to reduce dense-network clutter.", "Para relações entre folhas de uma hierarquia.", "For relationships among leaves of a hierarchy.", "Pode sugerir caminhos inexistentes e ocultar conexões individuais.", "It can imply nonexistent paths and hide individual links.", "hierarquia + conexões", "hierarchy + connections", [], ["grafo"]),
  viz("flowchart", "Fluxograma", "Flow chart", "flow", "basic", "Representa etapas, decisões e caminhos de um processo.", "Represents steps, decisions, and paths in a process.", "Para explicar lógica, procedimentos e jornadas.", "To explain logic, procedures, and journeys.", "Não é gerado adequadamente a partir de uma tabela genérica.", "It is not adequately generated from a generic table.", "nós + tipo + origem/destino", "nodes + type + source/target", [], ["processo"]),
  viz("choropleth", "Mapa coroplético", "Choropleth map", "geo", "intermediate", "Preenche regiões geográficas por uma escala de cor.", "Fills geographic regions using a color scale.", "Para taxas ou valores normalizados por território.", "For rates or normalized values by territory.", "Contagens absolutas favorecem áreas populosas; não use arco-íris.", "Absolute counts favor populous areas; avoid rainbow palettes.", "id geográfico + valor + geometria", "geographic id + value + geometry", [], ["mapa"]),
  viz("bubble-map", "Mapa de símbolos proporcionais", "Bubble map", "geo", "intermediate", "Posiciona círculos em locais e dimensiona sua área por valor.", "Places circles at locations and scales their area by value.", "Para contagens pontuais ou por centróides territoriais.", "For point counts or territorial centroids.", "Bolhas sobrepostas e áreas grandes podem ocultar locais.", "Overlapping bubbles and large areas can hide locations.", "latitude + longitude + valor", "latitude + longitude + value", ["proportional symbol map"], ["mapa"]),
  viz("dot-map", "Mapa de pontos", "Dot map", "geo", "intermediate", "Representa ocorrências ou unidades por pontos geográficos.", "Represents occurrences or units as geographic dots.", "Para distribuição espacial e concentração.", "For spatial distribution and concentration.", "Proteja dados sensíveis e explique se pontos são exatos ou agregados.", "Protect sensitive data and state whether points are exact or aggregated.", "latitude + longitude; categoria opcional", "latitude + longitude; optional category", [], ["mapa"]),
  viz("flow-map", "Mapa de fluxos", "Flow map", "geo", "advanced", "Combina localização e conexões direcionais de magnitude variável.", "Combines location with directional connections of varying magnitude.", "Para migração, comércio, transporte e deslocamentos.", "For migration, trade, transport, and movement.", "Muitos fluxos se sobrepõem; use filtros e agregação.", "Too many flows overlap; use filters and aggregation.", "origem/destino geográficos + peso", "geographic source/target + weight", ["connection map"], ["mapa", "fluxo"]),
  viz("hexbin-map", "Mapa hexbin", "Hexbin map", "geo", "advanced", "Agrega pontos em células hexagonais regulares.", "Aggregates points into regular hexagonal cells.", "Para densidade espacial com muitos pontos.", "For spatial density with many points.", "Tamanho da célula altera o padrão e deve ser informado.", "Cell size changes the pattern and must be disclosed.", "latitude + longitude", "latitude + longitude", [], ["mapa", "densidade"]),
  viz("cartogram", "Cartograma", "Cartogram", "geo", "advanced", "Distorce áreas territoriais de acordo com uma variável.", "Distorts territorial areas according to a variable.", "Para enfatizar magnitude em vez de forma geográfica.", "To emphasize magnitude rather than geographic shape.", "Pode dificultar o reconhecimento; inclua mapa de referência.", "It can hinder recognition; include a reference map.", "id geográfico + valor + geometria", "geographic id + value + geometry", [], ["mapa"]),
  viz("candlestick", "Candlestick", "Candlestick chart", "finance", "intermediate", "Resume abertura, máxima, mínima e fechamento por período.", "Summarizes open, high, low, and close values per period.", "Para séries financeiras ou qualquer dado OHLC.", "For financial series or any OHLC data.", "Não substitui contexto de volume e risco; use cores acessíveis.", "It does not replace volume and risk context; use accessible colors.", "data + abertura + máxima + mínima + fechamento", "date + open + high + low + close", [], ["OHLC"]),
  viz("ohlc", "OHLC", "OHLC chart", "finance", "intermediate", "Usa hastes e marcas laterais para quatro preços por período.", "Uses stems and side ticks for four prices per period.", "Para leitura compacta de séries financeiras.", "For compact financial time-series reading.", "É menos familiar ao público geral que candlesticks.", "It is less familiar to general audiences than candlesticks.", "data + abertura + máxima + mínima + fechamento", "date + open + high + low + close", ["open-high-low-close"], ["mercado"]),
  viz("kagi", "Kagi", "Kagi chart", "finance", "advanced", "Muda direção apenas quando o preço reverte por um limiar definido.", "Changes direction only when price reverses by a defined threshold.", "Para reduzir ruído temporal e observar reversões.", "To reduce time noise and inspect reversals.", "O limiar é uma escolha analítica crítica e o tempo não é uniforme.", "The threshold is analytically critical and time is not uniform.", "sequência temporal + preço + limiar", "time sequence + price + threshold", [], ["mercado"]),
  viz("point-figure", "Ponto e figura", "Point & figure", "finance", "advanced", "Registra movimentos relevantes de preço em colunas de X e O.", "Records meaningful price moves in columns of X and O.", "Para tendência e reversão sem escala temporal regular.", "For trend and reversal without a regular time scale.", "Tamanho de caixa e reversão mudam radicalmente o resultado.", "Box size and reversal settings radically change the result.", "sequência de preços + tamanho de caixa", "price sequence + box size", [], ["mercado"]),
  viz("funnel", "Funil", "Funnel chart", "finance", "basic", "Mostra redução de quantidade em etapas sequenciais.", "Shows quantity decreasing through sequential stages.", "Para conversão, recrutamento e processos com abandono.", "For conversion, recruitment, and drop-off processes.", "Etapas precisam ser realmente sequenciais e comparáveis.", "Stages must be truly sequential and comparable.", "etapa ordenada + valor", "ordered stage + value", [], ["processo"]),
  viz("word-cloud", "Nuvem de palavras", "Word cloud", "text", "basic", "Dimensiona palavras por frequência ou peso.", "Scales words by frequency or weight.", "Para visão rápida, exploratória e comunicacional de termos dominantes.", "For a quick exploratory or communicative view of dominant terms.", "É imprecisa para comparação; palavras longas ganham destaque visual.", "It is imprecise for comparison; long words gain visual prominence.", "texto bruto ou termo + frequência", "raw text or term + frequency", ["tag cloud"], ["texto"]),
  viz("term-frequency", "Frequência de termos", "Term frequency", "text", "basic", "Ordena termos por contagem ou medida de relevância.", "Ranks terms by count or relevance measure.", "Quando comparação precisa importa mais que impacto decorativo.", "When precise comparison matters more than decorative impact.", "Frequência isolada ignora contexto e ambiguidade.", "Frequency alone ignores context and ambiguity.", "termo + frequência", "term + frequency", [], ["texto"]),
  viz("cooccurrence", "Rede de coocorrências", "Co-occurrence network", "text", "advanced", "Conecta termos que aparecem juntos segundo uma janela ou unidade textual.", "Connects terms that appear together within a window or text unit.", "Para explorar associações em corpus, documentos e entrevistas.", "To explore associations in corpora, documents, and interviews.", "O resultado depende da limpeza, janela e limiar escolhidos.", "Results depend on cleaning, window, and threshold choices.", "documento/texto ou termo A + termo B + peso", "document/text or term A + term B + weight", [], ["texto", "rede"]),
  viz("word-tree", "Árvore de palavras", "Word tree", "text", "advanced", "Mostra contextos que seguem ou antecedem uma expressão central.", "Shows contexts that follow or precede a focal phrase.", "Para explorar padrões frasais e concordâncias.", "To explore phrase patterns and concordances.", "Não representa importância sem contagem e contexto do corpus.", "It does not represent importance without counts and corpus context.", "corpus textual + termo-raiz", "text corpus + root term", [], ["texto"]),
  viz("brainstorm", "Mapa de ideias", "Brainstorm diagram", "text", "basic", "Organiza ideias livres ao redor de temas e relações.", "Organizes free ideas around themes and relationships.", "Para ideação, síntese e organização conceitual.", "For ideation, synthesis, and conceptual organization.", "Não confunda proximidade visual com evidência quantitativa.", "Do not confuse visual proximity with quantitative evidence.", "nós + relação ou edição manual", "nodes + relationship or manual editing", ["mind map"], ["conceitos"]),
];

export const getEntry = (id: string) => catalog.find((entry) => entry.id === id) ?? catalog[0];

