import type { Locale } from "../catalog";

const pt = {
  fab: "Assistente de IA",
  title: "Assistente DataVizLab",
  aiBadge: "IA",
  close: "Fechar assistente",
  newChat: "Nova conversa",
  settings: "Configurações do assistente",
  // Onboarding / disclaimers
  introKicker: "Antes de começar",
  introTitle: "Um assistente de IA para seus dados",
  aiNoticeTitle: "Você está conversando com uma IA",
  aiNotice: "Este assistente é um sistema de inteligência artificial, não uma pessoa. As respostas são geradas automaticamente por um modelo de linguagem de terceiros e podem conter erros, omissões ou vieses. Confira informações importantes antes de usá-las. Aviso de transparência alinhado às boas práticas de gestão de sistemas de IA (ISO/IEC 42001).",
  dataNoticeTitle: "O que acontece com seus dados",
  dataNotice: "Fora do assistente, o DataVizLab processa tudo no seu dispositivo. Ao usar o assistente, suas mensagens e — conforme o nível de compartilhamento que você escolher — nomes, estrutura, estatísticas ou linhas dos seus projetos são enviados diretamente do seu navegador ao provedor de IA escolhido (por exemplo OpenRouter, OpenAI ou Anthropic), sob os termos e a política de privacidade dele. O DataVizLab não tem servidor e não guarda essas conversas. Não envie dados pessoais, sensíveis ou confidenciais sem autorização.",
  actionsNoticeTitle: "Ações sempre com sua confirmação",
  actionsNotice: "O assistente pode propor ações no DataVizLab — editar dados, trocar visualizações, criar ou excluir projetos, exportar. Nada é executado sem sua aprovação, e as ações aplicadas podem ser desfeitas.",
  keyNotice: "Chaves de API ficam apenas neste navegador.",
  acknowledge: "Li e entendi os avisos acima",
  continue: "Continuar",
  // Connection
  connectKicker: "Conectar um provedor",
  connectTitle: "Como você quer usar a IA?",
  oauthTitle: "Entrar com OpenRouter",
  oauthText: "Login seguro (OAuth com PKCE), sem copiar chaves. Uma conta OpenRouter dá acesso a centenas de modelos.",
  oauthButton: "Entrar com OpenRouter",
  byokTitle: "Usar minha chave (BYOK)",
  byokText: "Use a chave de API do seu provedor. A cobrança acontece diretamente na sua conta.",
  provider: "Provedor",
  apiKey: "Chave de API",
  getKey: "Obter uma chave",
  showKey: "Mostrar chave",
  hideKey: "Ocultar chave",
  remember: "Lembrar neste dispositivo",
  rememberHint: "Sem isso, a chave some ao fechar a aba",
  connect: "Conectar",
  connecting: "Conectando…",
  insecure: "O login exige uma conexão segura (HTTPS ou localhost).",
  oauthFailed: "Não foi possível concluir o login no OpenRouter.",
  // Chat
  model: "Modelo",
  searchModels: "Buscar modelos…",
  sharing: "Dados compartilhados com a IA",
  sharingNone: "Nenhum",
  sharingSchema: "Estrutura",
  sharingFull: "Completo",
  sharingNoneHint: "Só nomes de projetos e visualizações.",
  sharingSchemaHint: "Colunas, tipos e estatísticas — sem valores de linhas.",
  sharingFullHint: "Inclui valores das linhas, quando a IA pedir.",
  disconnect: "Desconectar",
  connectedVia: "Conectado via",
  emptyTitle: "Olá! Sou uma IA.",
  emptyText: "Posso analisar os dados dos seus projetos, sugerir visualizações, explicar conceitos de ciência de dados e fazer alterações no DataVizLab — sempre pedindo sua confirmação antes.",
  suggestions: ["Resuma os dados do projeto aberto", "Qual gráfico funciona melhor para estes dados?", "Há valores ausentes ou outliers?", "Explique a diferença entre média e mediana aqui"],
  placeholder: "Pergunte sobre seus dados ou peça uma ação…",
  send: "Enviar",
  stop: "Parar",
  thinking: "Pensando…",
  generatedBy: "Gerado por IA",
  footer: "Respostas geradas por IA podem conter erros. Dados enviados a",
  confirmTitle: "Ações propostas — confirme para executar",
  actionsTitle: "Ações propostas",
  confirmAll: "Confirmar",
  declineAll: "Recusar",
  statusPending: "Aguardando",
  statusRunning: "Executando…",
  statusDone: "Aplicada",
  statusDeclined: "Recusada",
  statusError: "Falhou",
  statusUndone: "Desfeita",
  undo: "Desfazer",
  refused: "O modelo recusou esta solicitação.",
  truncated: "A resposta foi interrompida por limite de tamanho.",
  stepLimit: "Parei após muitas etapas seguidas. Peça para continuar, se quiser.",
  errAuth: "Chave inválida ou sem permissão. Verifique a chave nas configurações.",
  errRate: "Limite de uso do provedor atingido. Tente novamente em instantes.",
  errNetwork: "Não foi possível falar com o provedor (rede ou bloqueio CORS do navegador).",
  errOther: "O provedor retornou um erro:",
};

type AiStrings = typeof pt;

const en: AiStrings = {
  fab: "AI assistant",
  title: "DataVizLab assistant",
  aiBadge: "AI",
  close: "Close assistant",
  newChat: "New conversation",
  settings: "Assistant settings",
  introKicker: "Before you start",
  introTitle: "An AI assistant for your data",
  aiNoticeTitle: "You are talking to an AI",
  aiNotice: "This assistant is an artificial intelligence system, not a person. Answers are generated automatically by a third-party language model and may contain errors, omissions or bias. Check important information before relying on it. Transparency notice aligned with AI management-system good practice (ISO/IEC 42001).",
  dataNoticeTitle: "What happens to your data",
  dataNotice: "Outside the assistant, DataVizLab processes everything on your device. When you use the assistant, your messages and — depending on the sharing level you choose — names, structure, statistics or rows of your projects are sent directly from your browser to the AI provider you pick (e.g. OpenRouter, OpenAI or Anthropic), under that provider's terms and privacy policy. DataVizLab has no server and does not keep these conversations. Do not send personal, sensitive or confidential data without authorization.",
  actionsNoticeTitle: "Actions always need your approval",
  actionsNotice: "The assistant can propose actions in DataVizLab — edit data, change visualizations, create or delete projects, export. Nothing runs without your approval, and applied actions can be undone.",
  keyNotice: "API keys stay in this browser only.",
  acknowledge: "I have read and understood these notices",
  continue: "Continue",
  connectKicker: "Connect a provider",
  connectTitle: "How do you want to use AI?",
  oauthTitle: "Sign in with OpenRouter",
  oauthText: "Secure sign-in (OAuth with PKCE), no key copying. One OpenRouter account gives access to hundreds of models.",
  oauthButton: "Sign in with OpenRouter",
  byokTitle: "Use my own key (BYOK)",
  byokText: "Use your provider's API key. Usage is billed directly to your account.",
  provider: "Provider",
  apiKey: "API key",
  getKey: "Get a key",
  showKey: "Show key",
  hideKey: "Hide key",
  remember: "Remember on this device",
  rememberHint: "Otherwise the key is gone when the tab closes",
  connect: "Connect",
  connecting: "Connecting…",
  insecure: "Sign-in needs a secure connection (HTTPS or localhost).",
  oauthFailed: "Could not complete the OpenRouter sign-in.",
  model: "Model",
  searchModels: "Search models…",
  sharing: "Data shared with the AI",
  sharingNone: "None",
  sharingSchema: "Structure",
  sharingFull: "Complete",
  sharingNoneHint: "Only project and visualization names.",
  sharingSchemaHint: "Columns, types and statistics — no row values.",
  sharingFullHint: "Includes row values when the AI asks for them.",
  disconnect: "Disconnect",
  connectedVia: "Connected via",
  emptyTitle: "Hi! I am an AI.",
  emptyText: "I can analyze your project data, suggest visualizations, explain data-science concepts and make changes in DataVizLab — always asking for your approval first.",
  suggestions: ["Summarize the open project's data", "Which chart works best for this data?", "Are there missing values or outliers?", "Explain mean vs. median for this data"],
  placeholder: "Ask about your data or request an action…",
  send: "Send",
  stop: "Stop",
  thinking: "Thinking…",
  generatedBy: "AI-generated",
  footer: "AI-generated answers may contain mistakes. Data sent to",
  confirmTitle: "Proposed actions — approve to run",
  actionsTitle: "Proposed actions",
  confirmAll: "Approve",
  declineAll: "Decline",
  statusPending: "Waiting",
  statusRunning: "Running…",
  statusDone: "Applied",
  statusDeclined: "Declined",
  statusError: "Failed",
  statusUndone: "Undone",
  undo: "Undo",
  refused: "The model declined this request.",
  truncated: "The answer was cut off by the length limit.",
  stepLimit: "I stopped after many steps in a row. Ask me to continue if you want.",
  errAuth: "Invalid key or missing permission. Check the key in settings.",
  errRate: "The provider's rate limit was reached. Try again shortly.",
  errNetwork: "Could not reach the provider (network or the browser's CORS policy).",
  errOther: "The provider returned an error:",
};

export const aiStrings = (locale: Locale): AiStrings => (locale === "pt" ? pt : en);
export type { AiStrings };
