// Pre-renders every catalog thumbnail as a static SVG (public/thumbs/{theme}/{locale}/{id}.svg), so the
// catalog shows real charts without running ECharts in the browser. Thumbnails are deterministic (each
// chart's own sample data), so they only change when a chart builder or a sample changes.
// Usage: npm run thumbs            (regenerates the files)
//        npm run thumbs -- --check (fails if the committed files are stale)
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { chartThumbnail } from "../components/chartThumb";
import { catalog, type Locale } from "../lib/catalog";

export const THEMES = ["dark", "light"] as const;
export const LOCALES: Locale[] = ["pt", "en"];

/** The thumbnail file for one chart, with element ids that do not depend on render order. */
export const thumbnailFile = (id: string, locale: Locale, theme: (typeof THEMES)[number]) =>
  chartThumbnail(id, locale, theme === "dark").replace(/\bzr\d+-/g, `t-${id}-`);

export function buildThumbnails(root = "public/thumbs") {
  const files = new Map<string, string>();
  for (const theme of THEMES) for (const locale of LOCALES) for (const entry of catalog) files.set(join(root, theme, locale, `${entry.id}.svg`), thumbnailFile(entry.id, locale, theme));
  const version = createHash("sha1").update([...files.values()].join("\n")).digest("hex").slice(0, 10);
  // Thumbnails that contain text are inlined by the page, since an <img> would not use the page's web fonts.
  const withText = [...new Set([...files].filter(([, svg]) => svg.includes("<text")).map(([path]) => basename(path, ".svg")))].sort();
  const versionModule = `// Generated by scripts/build-thumbnails.ts; do not edit.\nexport const THUMBS_VERSION = "${version}";\nexport const TEXT_THUMBS: ReadonlySet<string> = new Set(${JSON.stringify(withText)});\n`;
  return { files, version, versionModule };
}

const VERSION_MODULE = "components/thumbs.generated.ts";

if (process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/build-thumbnails.ts")) {
  const { files, versionModule } = buildThumbnails();
  const stale = [...files].filter(([path, svg]) => !existsSync(path) || readFileSync(path, "utf8") !== svg).map(([path]) => path);
  const versionStale = !existsSync(VERSION_MODULE) || readFileSync(VERSION_MODULE, "utf8") !== versionModule;
  if (process.argv.includes("--check")) {
    if (stale.length || versionStale) { console.error(`${stale.length} thumbnails are stale; run npm run thumbs`); process.exit(1); }
    console.log(`${files.size} thumbnails up to date`);
  } else {
    for (const [path, svg] of files) { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, svg); }
    writeFileSync(VERSION_MODULE, versionModule);
    const bytes = [...files.values()].reduce((sum, svg) => sum + svg.length, 0);
    console.log(`${files.size} thumbnails written (${Math.round(bytes / 1024)} KB), ${stale.length} changed`);
  }
}
